# Generated by Django 3.2.4 on 2021-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp2', '0003_auto_20210721_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammal',
            name='gender',
            field=models.CharField(choices=[('male', 'female')], max_length=100),
        ),
    ]
