# Generated by Django 4.0.6 on 2022-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texts',
            old_name='text',
            new_name='username',
        ),
        migrations.AddField(
            model_name='texts',
            name='email',
            field=models.TextField(default='Default  email', null=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='images/'),
        ),
    ]
