# Generated by Django 4.0.6 on 2022-07-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_text_texts_username_texts_email_texts_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
