# Generated by Django 4.0.6 on 2022-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Default text', null=True)),
            ],
            options={
                'verbose_name_plural': 'Articles ',
                'ordering': ['id'],
            },
        ),
    ]
