# Generated by Django 4.0.6 on 2022-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('1', 'Technology'), ('2', 'Business'), ('3', 'Entertainment'), ('4', 'General'), ('5', 'Health'), ('6', 'Science'), ('7', 'Sports'), ('8', 'Travel'), ('9', 'World'), ('10', 'Politics')], default='1', max_length=100),
        ),
    ]
