# Generated by Django 4.0.6 on 2022-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
