# Generated by Django 4.0.6 on 2022-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_articles_category_remove_articles_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('General', 'General'), ('Health', 'Health'), ('Science', 'Science'), ('Sports', 'Sports'), ('Travel', 'Travel'), ('World', 'World'), ('Politics', 'Politics')], default='General', max_length=255),
        ),
    ]
