# Generated by Django 3.0.4 on 2022-08-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Default text', null=True)),
            ],
            options={
                'verbose_name_plural': 'RealEstate',
                'ordering': ['id'],
            },
        ),
    ]
