# Generated by Django 3.0.4 on 2022-08-26 08:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='text',
        ),
        migrations.AddField(
            model_name='realestate',
            name='json',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
