# Generated by Django 3.0.4 on 2022-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220826_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='json',
        ),
    ]
