# Generated by Django 3.0.4 on 2022-08-26 17:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_realestate_json'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realestate',
            managers=[
                ('dict_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
