# Generated by Django 3.0.4 on 2022-08-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220826_2258'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realestate',
            managers=[
            ],
        ),
    ]
