
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from jsonfield import JSONField

class RealEstate(models.Model):
   
    """
    # id  column is always autogenerated by django 
    # create your models columns accordingly
    """

    json = JSONField(null=False, blank=False, default={})
    
    class Meta :
        verbose_name_plural =  "RealEstate"    
        ordering = ['id']                      #  'Given column ID wise ordering'

    def __str__(self):
        return str(self.id)                    #  'Cant return int or None here else error'


