# Generated by Django 3.2.5 on 2021-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('prod_avail', models.BooleanField(default=True)),
            ],
        ),
    ]
