# Generated by Django 3.2.4 on 2021-07-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp2', '0005_alter_mammal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='id',
        ),
        migrations.AlterField(
            model_name='fish',
            name='species',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
